<?php
/**
 * @file
 * The main module file.
 *
 */

define('_PARSELY_VERSION', '0.1');

/**
 * Implements hook_init().
 */
function parsely_init() {
  $apikey = variable_get('parsely_apikey', '');

  if (parsely_should_add_metas()) {
    $parsely_meta = _parsely_get_node_metadata();
    drupal_add_html_head(array(
      '#tag' => 'script',
      '#attributes' => array('type' => 'application/ld+json'),
      '#value' => json_encode($parsely_meta),
    ), 'parsely_metadata');
    drupal_add_html_head(array(
      '#tag' => 'meta',
      '#attributes' => array(
        'name' => 'drupal_parsely_version',
        'id' => 'drupal_parsely_version',
        'content' => _PARSELY_VERSION
      )
    ), 'parsely_version');
  }
}

/**
 * Implements hook_menu().
 */
function parsely_menu() {
  $items['admin/config/system/parsely'] = array(
    'title'            => 'Parse.ly',
    'description'      => 'Parse.ly configuration settings.',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('parsely_admin_settings'),
    'access arguments' => array('administer parsely settings'),
    'type'             => MENU_NORMAL_ITEM,
    'file'             => 'parsely.admin.inc',
  );
  $items['admin/config/system/parsely/settings'] = array(
    'title' => 'Settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function parsely_permission() {
  return array(
  'administer parsely settings' => array(
    'title' => t('Administer Parse.ly settings'),
  ),
  );
}

/**
 * Determines whether or not to place the parsely meta tag on a page. This is
 * separate from should_track because we don't need to consider whether users
 * are authenticated here.
 */
function parsely_should_add_metas() {
  // @todo: This needs to work on non-node pages.
  $node = menu_get_object();
  if ($node === NULL) {
    return FALSE;
  }

  $parsely_api_key = variable_get('parsely_apikey', '');
  if (empty($parsely_api_key)) {
    return FALSE;
  }

  $path = drupal_strtolower(drupal_get_path_alias($_GET['q']));
  if (drupal_match_path($path, implode("\r", parsely_paths_to_ignore()))) {
    return FALSE;
  }

  return TRUE;
}

/**
 * Determines whether or not to place the Parsely JavaScript on a page.
 */
function parsely_should_track() {
  if (!parsely_should_add_metas()) {
    return FALSE;
  }

  // Check whether or not we should track logged in users
  $should_track_authenticated_users = variable_get('parsely_track_authenticated_users') === '0';
  if ($should_track_authenticated_users && _parsely_user_is_authenticated()) {
    return FALSE;
  }

  return TRUE;
}

/**
 * Returns an array of paths not to track using Parse.ly's javascript/metadata
 * tags.
 */
function parsely_paths_to_ignore() {
  return array(
    'admin*',
    'node/add*',
    'node/*/edit*',
    'node/*/delete*',
  );
}

/**
 * Implements hook_page_build to insert Parse.ly's JavaScript tracker.
 */
function parsely_page_build(&$page) {
  if (!parsely_should_track()) {
    return;
  }

  $apikey = check_plain(variable_get('parsely_apikey'));
  $markup = <<<EOT

<!-- START Parse.ly Include: Standard -->
<div id="parsely-root" style="display: none">
  <div id="parsely-cfg" data-parsely-site="$apikey"></div>
</div>
<script>
(function(s, p, d) {
  var h=d.location.protocol, i=p+"-"+s,
    e=d.getElementById(i), r=d.getElementById(p+"-root"),
    u=h==="https:"?"d1z2jf7jlzjs58.cloudfront.net"
    :"static."+p+".com";
  if (e) return;
  e = d.createElement(s); e.id = i; e.async = true;
  e.src = h+"//"+u+"/p.js"; r.appendChild(e);
})("script", "parsely", document);
</script>
<!-- END Parse.ly Include: Standard -->
EOT;
  $page['page_bottom']['parsely'] = array('#markup' => $markup);
}


function _parsely_user_is_authenticated() {
  // Anonymous users have a uid of 0, anyone else is authenticated
  global $user;
  return $user->uid !== 0;
}

/*** Parsely Metadata Functions **********************************************/
function _parsely_get_content_id($node) {
  $prefix = variable_get('parsely_content_id_prefix', '');
  if (!empty($prefix))
    $prefix = $prefix . '-';

  return $prefix.$node->nid;
}

function _parsely_get_canonical_url($node) {
  $uri = entity_uri('node', $node);
  return url($uri['path'], array_merge($uri['options'], array('absolute' => TRUE)));
}

function _parsely_get_authors($node) {
  return array($node->name);
}

function _parsely_get_pub_date_utc($node) {
  $pub_date = NULL;
  // Prefer published_at which is added by the publication_date module
  // https://www.drupal.org/project/publication_date
  if (property_exists($node, 'published_at') && is_numeric($node->published_at)) {
    $pub_date = $node->published_at;
  }
  // Otherwise, fall back to just Drupal's created date
  else {
    $pub_date = $node->created;
  }

  return gmdate("Y-m-d\TH:i:s\Z", $pub_date);
}

/**
 * Attempt to determine the "section" to which a given node belongs.
 */
function _parsely_get_section($node) {
  $section_name = 'Uncategorized';
  $section_term = NULL;
  $section_vocabulary_id = variable_get('parsely_section_vocabulary');

  if (module_exists('taxonomy') && !is_null($section_vocabulary_id)) {
    // Find the most relevant term from the designated vocab, using the
    // criterion specified in the module configuration. See
    // parsely_admin_settings() for an explanation of the supported criteria.
    $selection_criterion = variable_get('parsely_section_term_criterion', 'first');

    $section_term_query = db_select('taxonomy_index', 'ti');
    $section_term_query->join('taxonomy_term_data', 'ttd', 'ti.tid=ttd.tid');
    $section_term_query->fields('ttd', array('tid'))
      ->condition('ti.nid', $node->nid)
      ->condition('ttd.vid', $section_vocabulary_id);

    // "First term" or "Last term."
    if ($selection_criterion == 'first' || $selection_criterion == 'last') {
      $sort_direction = ($selection_criterion == 'first') ? 'ASC' : 'DESC';
      $section_term_query->orderBy('ttd.tid', $sort_direction)
        ->range(0, 1);
      $section_term_result = $section_term_query->execute();

      if ($section_term_result->rowCount() > 0) {
        $section_tid = $section_term_result->fetchField();
        $section_term = taxonomy_term_load($section_tid);
      }
    }
    // "Highest-level term."
    elseif ($selection_criterion == 'highest') {
      $all_terms_result = $section_term_query->orderBy('ttd.tid')
        ->execute();

      if ($all_terms_result->rowCount() > 0) {
        $tids = $all_terms_result->fetchCol();
        $terms = taxonomy_term_load_multiple($tids);
        // Examine each term and see how many parents it has. We could use
        // taxonomy_get_tree() to get the depths of every term in the vocab,
        // but that could be problematic for large vocabs.
        foreach ($terms as $term) {
          // Calculate depth by repeatedly calling taxonomy_get_parents(). This
          // is preferable to calling taxonomy_get_parents_all(), because that
          // would include all parents of any multi-parent terms, skewing our
          // generation count. Note that $depth will be "1" for a top-level term
          // here instead of the conventional "0."
          $t = $term;
          $depth = 0;
          while (!is_null($t)) {
            $depth++;
            $parents = taxonomy_get_parents($t->tid);
            $t = array_pop($parents);
          }
          if (!isset($highest_term) || $depth < $highest_term->depth) {
            $term->depth = $depth;
            $highest_term = $term;
          }
        }
        $section_term = $highest_term;
      }
    }
    // "Highest-level ancestor."
    elseif ($selection_criterion == 'ancestor') {
      $first_term_result = $section_term_query->orderBy('ti.created')
        ->range(0, 1)
        ->execute();

      if ($first_term_result->rowCount() > 0) {
        $first_term_tid = $first_term_result->fetchField();
        $lineage = taxonomy_get_parents_all($first_term_tid);
        $section_term = array_pop($lineage);
      }
    }
  }

  if (property_exists($section_term, 'name')) {
    $section_name = $section_term->name;
  }

  // Allow any module to alter the section name.
  drupal_alter('parsely_section', $section_name, $node, $section_term);

  return $section_name;
}

function _parsely_get_tags($node) {
  $supported_vocabularies = variable_get('parsely_tag_vocabularies');
  if (!module_exists('taxonomy') || $supported_vocabularies === NULL) {
    return array();
  }

  // Fetch the names of all terms that (a) belong to one of the supported
  // vocabularies and (b) are associated with the given node.
  $active_terms_query = db_select('taxonomy_index', 'ti');
  $active_terms_query->join('taxonomy_term_data', 'ttd', 'ti.tid=ttd.tid');
  $active_terms_result = $active_terms_query->fields('ttd', array('name'))
    ->condition('ti.nid', $node->nid)
    ->condition('ttd.vid', $supported_vocabularies, 'IN')
    ->execute();

  $active_terms = array();
  if ($active_terms_result->rowCount() > 0) {
    $active_terms = $active_terms_result->fetchCol();
  }

  return $active_terms;
}

function _parsely_get_node_metadata() {
  $node = menu_get_object();

  // @todo: Integrate with metatag module and/or support more tokens, etc.
  $parsely_meta = array(
    '@context'       => 'http://schema.org',
    '@type'          => 'WebPage',
    'articleId'      => _parsely_get_content_id($node),
    'headline'       => $node->title,
    'url'            => _parsely_get_canonical_url($node),
    'dateCreated'    => _parsely_get_pub_date_utc($node),
    'articleSection' => _parsely_get_section($node),
    'creator'        => _parsely_get_authors($node),
    'keywords'       => _parsely_get_tags($node),
  );

  if ($thumbnail_url = variable_get('parsely_metadata_thumbnail_url', FALSE)) {
    $thumbnail_url = token_replace($thumbnail_url, array('node' => $node));
    if (!empty($thumbnail_url)) {
      $parsely_meta['thumbnailUrl'] = $thumbnail_url;
    }
  }

  // @todo: Allow admins to customize the @type value.
  if ($node->type === 'article') {
    $parsely_meta['@type'] = 'NewsArticle';
  }

  // @todo: Also support the "metadata" key so users can pass in any additional custom data.

  return $parsely_meta;
}
